name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: false

jobs:
  build:
    runs-on: windows-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Build (Release)
      run: dotnet build Vortice.Windows.Samples.sln -c Release
